version: '3' 
services: 
    fastapi: 
        build: ./backend 
        image: fastapi:latest
        ports: 
            - "80:80"
        volumes:
            - /home/ubuntu/images/profile:/static/image/profile
            - /home/ubuntu/images/diary:/static/image/diary